# Generated by Django 3.1.5 on 2021-01-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images', verbose_name=''),
        ),
    ]
