# Generated by Django 3.1.5 on 2021-01-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_projectmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
