# Generated by Django 3.1.5 on 2021-01-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='directory/%Y/%m/%d')),
                ('directory_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
