# Generated by Django 3.1.5 on 2021-01-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
